apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservicea
spec:
  ingressClassName: nginx
  rules:
    - host: myservicea.foo.org
      http:
        paths:
          - path: /
            backend:
              serviceName: example-service
              servicePort: 80